import type { MetadataRoute } from "next";
import { IS_CANONICAL_HOST, absoluteUrl } from "@/lib/seo";
import { ROUTES } from "@/lib/routes";

// Generated rather than a static file so it can depend on which host this
// deployment is serving: only jobzshala.ae and www.jobzshala.ae invite crawlers.
// Any other subdomain (dev./staging.) or domain disallows everything, so preview
// environments never get indexed or compete with the real site.

// Paths with no public content — authenticated areas, the admin console and the
// API. Applied to every user agent. Employer equivalents are listed explicitly
// because that app is a separate deployment under /hire and can't serve its own
// robots.txt (only the domain root's counts).
const DISALLOWED = [
  "/admin",
  "/api/",
  "/api-docs",
  // The old shared "/dashboard" prefix covered these with one entry; now
  // that they're flat top-level routes (see app/(app)/), each needs its own.
  ROUTES.journey,
  ROUTES.profile,
  ROUTES.matches,
  ROUTES.applications,
  ROUTES.subscription,
  ROUTES.documents,
  ROUTES.changePassword,
  ROUTES.resetPassword,
  ROUTES.forgotPassword,
  "/hire/dashboard",
  "/hire/change-password",
  "/hire/reset-password",
  "/hire/forgot-password",
  "/hire/verify-email",
  "/hire/sparkles-demo",
];

// AI answer-engine / LLM crawlers — explicitly welcomed with the same access as
// regular search bots, so the platform can be surfaced and cited in
// AI-generated answers (ChatGPT, Perplexity, Google AI Overviews, Claude).
const AI_CRAWLERS = [
  "GPTBot",
  "ChatGPT-User",
  "OAI-SearchBot",
  "ClaudeBot",
  "anthropic-ai",
  "PerplexityBot",
  "Google-Extended",
  "Applebot-Extended",
];

export default function robots(): MetadataRoute.Robots {
  if (!IS_CANONICAL_HOST) {
    return { rules: [{ userAgent: "*", disallow: "/" }] };
  }

  return {
    rules: [
      { userAgent: "*", allow: ["/", "/hire"], disallow: DISALLOWED },
      { userAgent: AI_CRAWLERS, allow: ["/", "/hire"], disallow: DISALLOWED },
    ],
    // Two sitemaps: this app's, plus the employer app's, which is generated by
    // jobzshala-gcc-employer/app/sitemap.ts and served under its /hire basePath.
    // robots.txt only exists at the domain root, so it has to be listed here.
    sitemap: [absoluteUrl("/sitemap.xml"), absoluteUrl("/hire/sitemap.xml")],
    host: absoluteUrl("/"),
  };
}
